# Chapter 2 — Linear Algebra for ML

**Goals**

- Read and write vectors and matrices in NumPy the way ML papers do.
- Compute inner products, matrix-vector and matrix-matrix products.
- Use the L1, L2, and L_inf norms.
- Compute Euclidean distance and cosine similarity between two points.
- Recognise the dot product hidden inside a linear model.

Pair with `docs/01_math_foundation.md` (Part A).

## 1. Setup

In [1]:
import numpy as np

SEED = 42
rng = np.random.default_rng(SEED)
np.set_printoptions(precision=4, suppress=True)

## 2. Vectors and matrices

A vector is a 1-D array; a matrix is a 2-D array. `.shape` tells you which is which.

In [2]:
x = np.array([1.0, 2.0, 3.0])
X = np.array([[1, 2, 3],
              [4, 5, 6]])
print('x shape =', x.shape)
print('X shape =', X.shape)
print('X[0, :] =', X[0, :])     # first row
print('X[:, 1] =', X[:, 1])     # second column

x shape = (3,)
X shape = (2, 3)
X[0, :] = [1 2 3]
X[:, 1] = [2 5]


## 3. Transpose

`X.T` swaps rows and columns. A column vector `(n,1)` transposes to a row vector `(1,n)`.

In [3]:
print('X      shape =', X.shape)
print('X.T    shape =', X.T.shape)
print('X.T:')
print(X.T)

X      shape = (2, 3)
X.T    shape = (3, 2)
X.T:
[[1 4]
 [2 5]
 [3 6]]


## 4. Inner product (dot product)

For $\mathbf{x}, \mathbf{y} \in \mathbb{R}^n$: $\mathbf{x}^\top \mathbf{y} = \sum_i x_i y_i$. Geometrically this is $\|\mathbf{x}\|\|\mathbf{y}\| \cos\theta$.

In [4]:
x = np.array([1.0, 2.0, 3.0])
y = np.array([4.0, 5.0, 6.0])
print('np.dot(x, y) =', np.dot(x, y))
print('x @ y        =', x @ y)
print('manual sum   =', sum(xi * yi for xi, yi in zip(x, y)))

np.dot(x, y) = 32.0
x @ y        = 32.0
manual sum   = 32.0


## 5. Matrix multiplication

$\mathbf{C} = \mathbf{A}\mathbf{B}$ where $\mathbf{A}$ is $m \times n$, $\mathbf{B}$ is $n \times p$, $\mathbf{C}$ is $m \times p$. The $(i, j)$ entry of $\mathbf{C}$ is the dot product of row $i$ of $\mathbf{A}$ with column $j$ of $\mathbf{B}$.

In [5]:
A = np.array([[1, 2],
              [3, 4],
              [5, 6]])      # 3 x 2
B = np.array([[7,  8,  9],
              [10, 11, 12]])# 2 x 3
C = A @ B                   # 3 x 3
print('A shape =', A.shape, '  B shape =', B.shape, '  C shape =', C.shape)
print('C =')
print(C)

A shape = (3, 2)   B shape = (2, 3)   C shape = (3, 3)
C =
[[ 27  30  33]
 [ 61  68  75]
 [ 95 106 117]]


## 6. Linear model: matrix-vector product

A dataset $\mathbf{X} \in \mathbb{R}^{N \times d}$ has one sample per row. The linear-model prediction across the whole dataset is
$$\hat{\mathbf{y}} = \mathbf{X}\mathbf{w} + b\mathbf{1}.$$

In [6]:
N, d = 5, 3
X = rng.standard_normal(size=(N, d))
w = np.array([0.5, -0.2, 1.0])
b = 0.1
y_hat = X @ w + b
print('X shape =', X.shape, '  w shape =', w.shape, '  y_hat shape =', y_hat.shape)
print('y_hat =', y_hat)

X shape = (5, 3)   w shape = (3,)   y_hat shape = (5,)
y_hat = [ 1.2108 -0.3417  0.2104  0.2754  0.3751]


## 7. Norms

- $\ell_1$ — sum of absolute values.
- $\ell_2$ — square-root of sum of squares (Euclidean length).
- $\ell_\infty$ — largest absolute value.

In [7]:
x = np.array([3.0, -4.0, 12.0])
print('L1 (manhattan)   :', np.linalg.norm(x, ord=1))
print('L2 (euclidean)   :', np.linalg.norm(x, ord=2))
print('Linf (max-abs)   :', np.linalg.norm(x, ord=np.inf))

L1 (manhattan)   : 19.0
L2 (euclidean)   : 13.0
Linf (max-abs)   : 12.0


## 8. Special matrices: identity and inverse

In [8]:
I = np.eye(3)
A = np.array([[4.0, 2.0],
              [1.0, 3.0]])
A_inv = np.linalg.inv(A)
print('I:\n', I)
print('A @ A_inv:\n', A @ A_inv)   # should be I

I:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
A @ A_inv:
 [[ 1.  0.]
 [-0.  1.]]


## 9. Eigenvalues and eigenvectors (intuition)

$\mathbf{A}\mathbf{v} = \lambda\mathbf{v}$: the matrix only scales $\mathbf{v}$ by the scalar $\lambda$, no rotation. These show up again in PCA and SVD (later chapters).

In [9]:
A = np.array([[2.0, 0.0],
              [0.0, 3.0]])
eigvals, eigvecs = np.linalg.eig(A)
print('eigvals =', eigvals)
print('eigvecs (columns):\n', eigvecs)

eigvals = [2. 3.]
eigvecs (columns):
 [[1. 0.]
 [0. 1.]]


## 10. CHECKPOINT — implement the four building blocks

Most of this course's algorithms boil down to four primitives. Implement each twice (NumPy + by hand) and compare.

### 10.1 Euclidean distance

In [10]:
def euclidean_distance(a: np.ndarray, b: np.ndarray) -> float:
    return float(np.sqrt(np.sum((a - b) ** 2)))

a = np.array([1.0, 2.0, 3.0])
b = np.array([4.0, 6.0, 3.0])
print('manual      :', euclidean_distance(a, b))
print('np.linalg   :', np.linalg.norm(a - b))

manual      : 5.0
np.linalg   : 5.0


### 10.2 Cosine similarity

In [11]:
def cosine_similarity(a: np.ndarray, b: np.ndarray) -> float:
    return float(a @ b / (np.linalg.norm(a) * np.linalg.norm(b)))

u = np.array([1.0, 0.0, 0.0])
v = np.array([1.0, 1.0, 0.0])
w = np.array([-1.0, 0.0, 0.0])
print('cos(u, v)   =', cosine_similarity(u, v))   # 0.7071
print('cos(u, u)   =', cosine_similarity(u, u))   # 1.0
print('cos(u, w)   =', cosine_similarity(u, w))   # -1.0

cos(u, v)   = 0.7071067811865475
cos(u, u)   = 1.0
cos(u, w)   = -1.0


### 10.3 Matrix-vector multiplication, by hand

In [12]:
def matvec(A: np.ndarray, x: np.ndarray) -> np.ndarray:
    m, n = A.shape
    assert x.shape == (n,), 'shape mismatch'
    out = np.zeros(m)
    for i in range(m):
        for j in range(n):
            out[i] += A[i, j] * x[j]
    return out

A = rng.standard_normal(size=(4, 3))
x = rng.standard_normal(size=(3,))
print('manual:', matvec(A, x))
print('A @ x :', A @ x)
assert np.allclose(matvec(A, x), A @ x)

manual: [-0.5749  0.2208  0.1892 -0.0725]
A @ x : [-0.5749  0.2208  0.1892 -0.0725]


### 10.4 L2 normalization

Mapping a vector to its unit-length version $\hat{\mathbf{x}} = \mathbf{x} / \|\mathbf{x}\|_2$ is a standard preprocessing step before computing cosine similarity in batch.

In [13]:
def l2_normalize(X: np.ndarray, axis: int = -1, eps: float = 1e-12) -> np.ndarray:
    norms = np.linalg.norm(X, axis=axis, keepdims=True)
    return X / np.maximum(norms, eps)

X = rng.standard_normal(size=(5, 3))
Xn = l2_normalize(X, axis=1)
print('row norms after normalization:', np.linalg.norm(Xn, axis=1))

row norms after normalization: [1. 1. 1. 1. 1.]


## 11. Summary

- A dataset is a matrix `X` of shape `(N, d)`. A linear model is `X @ w + b`.
- Dot products show up everywhere — predictions, similarities, gradient updates.
- L2 distance measures magnitude differences; cosine similarity measures angle only.
- L2 normalization makes rows comparable by angle.

**Next:** `notebooks/chapter_02_probability_gradient.ipynb` — probability for Naive Bayes and likelihood.